### ISSUE TITLE
inconsistent newline markers in code and documentation

### ISSUE THREAD

**Issue by jonassmedegaard** [jegoyalu/jarisplayer#12]
Recent git commits was done using DOS newlines (carry return + linefeed) whereas the common newline seems to be Unix style (linefeed).

Please consider cleaning up the mess.

**Comment by jgmdev** [comment]
actually the DOS newlines where already there but since I set geany to convert tabs to spaces it was more noticeable on the commit. I developed the player with flashdevelop and I guess that it uses that by default. In any case I modified all files to use unix line endings and retagged 2.0.17, also added a missing change on the changes file.

Thanks for reporting.
